table despesas_bi
	lineageTag: 70e08d92-b005-429a-b23d-5d902c672576

	measure 'Total Pago' = SUM('despesas_bi'[valor_pago])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 81d64da1-99e6-4dd9-974c-a5c9be77b685

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Empenhado' = SUM('despesas_bi'[valor_empenhado])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 912e7f8d-24a0-4df1-b883-cc062f54e919

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Liquidado' = SUM('despesas_bi'[valor_liquidado])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 1e100ebe-627e-4cd9-b85b-fa8751dfa27c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Restos a Pagar Pagos' = SUM('despesas_bi'[valor_restos_pagos])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f50114e5-e821-4c68-8423-bc04d457df04

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Quantidade de Registros' = COUNTROWS('despesas_bi')
		formatString: #,0
		lineageTag: 451ae0a9-6c88-4b41-ae40-0ba10eae0c70

	measure 'Total Pago Mês Anterior' =
			VAR Mes = MAX('Calendario'[InicioMes])
			RETURN IF(NOT ISBLANK(Mes),
			    CALCULATE([Total Pago], REMOVEFILTERS('Calendario'), 'Calendario'[InicioMes] = EDATE(Mes, -1)))
		formatString: "R$" #,0.00;-"R$" #,0.00;"R$" #,0.00
		lineageTag: 68c7ab27-4a74-4d99-a20c-0c9df3dce220

	measure 'Variação Mensal Pago R$' =
			VAR Mes = MAX('Calendario'[InicioMes])
			VAR Atual = CALCULATE([Total Pago], KEEPFILTERS('Calendario'[InicioMes] = Mes))
			VAR Anterior = [Total Pago Mês Anterior]
			RETURN IF(NOT ISBLANK(Atual) && NOT ISBLANK(Anterior), Atual - Anterior)
		formatString: "R$" #,0.00;-"R$" #,0.00;"R$" #,0.00
		lineageTag: 587b79e4-5adc-4971-8e74-92a0fd231c59

	measure 'Variação Mensal Pago %' =
			VAR Mes = MAX('Calendario'[InicioMes])
			VAR Atual = CALCULATE([Total Pago], KEEPFILTERS('Calendario'[InicioMes] = Mes))
			VAR Anterior = [Total Pago Mês Anterior]
			RETURN IF(NOT ISBLANK(Atual) && NOT ISBLANK(Anterior), DIVIDE(Atual - Anterior, Anterior))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 58ec278d-8a69-44c2-8f78-955e74d65671

	measure 'Total Pago Acumulado' =
			VAR Limite = MAX('Calendario'[Data])
			RETURN CALCULATE([Total Pago], FILTER(ALLSELECTED('Calendario'), 'Calendario'[Data] <= Limite))
		formatString: "R$" #,0.00;-"R$" #,0.00;"R$" #,0.00
		lineageTag: a11d7e3a-777c-404d-a242-962b293b081c

	measure 'Quantidade de Órgãos' = DISTINCTCOUNT('despesas_bi'[codigo_orgao_superior])
		formatString: #,0
		lineageTag: cb735c4d-b25a-49f3-a76b-070bc6a5adb3

	measure 'Quantidade de Programas' = DISTINCTCOUNT('despesas_bi'[codigo_programa])
		formatString: #,0
		lineageTag: 9e900648-4259-4839-8e08-bb972218ddff

	measure 'Subtítulo do Período' =
			VAR Meses = VALUES('Calendario'[InicioMes])
			VAR Quantidade = COUNTROWS(Meses)
			VAR Primeiro = MINX(Meses, 'Calendario'[InicioMes])
			VAR Ultimo = MAXX(Meses, 'Calendario'[InicioMes])
			VAR NomeInicial = FORMAT(Primeiro, "mmmm", "pt-BR")
			VAR NomeFinal = FORMAT(Ultimo, "mmmm", "pt-BR")
			VAR Inicial = UPPER(LEFT(NomeInicial, 1)) & MID(NomeInicial, 2, 30)
			VAR Final = UPPER(LEFT(NomeFinal, 1)) & MID(NomeFinal, 2, 30)
			VAR Continuo = Quantidade = DATEDIFF(Primeiro, Ultimo, MONTH) + 1
			VAR Periodo = SWITCH(TRUE(),
			    Quantidade = 0, "Sem período selecionado",
			    Quantidade = 1, Inicial & " de " & FORMAT(Primeiro, "yyyy"),
			    NOT Continuo, CONCATENATEX(Meses, FORMAT('Calendario'[InicioMes], "mmm/yyyy", "pt-BR"), ", ", 'Calendario'[InicioMes], ASC),
			    YEAR(Primeiro) = YEAR(Ultimo), Inicial & " a " & Final & " de " & FORMAT(Ultimo, "yyyy"),
			    Inicial & " de " & FORMAT(Primeiro, "yyyy") & " a " & Final & " de " & FORMAT(Ultimo, "yyyy"))
			RETURN "Execução da despesa federal — " & Periodo
		lineageTag: d6c77bf8-c7ea-4478-adc6-d8243fa62a9a

	column id_registro
		dataType: string
		lineageTag: 54250ad5-19ab-4167-9c35-5d1418b8f842
		summarizeBy: none
		sourceColumn: id_registro

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: dateTime
		formatString: Long Date
		lineageTag: c3d8ee12-44dd-4f4a-8b16-8282d3a0cba8
		summarizeBy: none
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column codigo_orgao_superior
		dataType: string
		lineageTag: 61bfa31e-2511-4b13-b812-9f2c439e9042
		summarizeBy: none
		sourceColumn: codigo_orgao_superior

		annotation SummarizationSetBy = Automatic

	column nome_orgao_superior
		dataType: string
		lineageTag: 0a7a46ee-4a46-4105-835c-d4aff737a618
		summarizeBy: none
		sourceColumn: nome_orgao_superior

		annotation SummarizationSetBy = Automatic

	column codigo_funcao
		dataType: string
		lineageTag: 4db5a5c3-08c9-46d8-9b49-299154266c30
		summarizeBy: none
		sourceColumn: codigo_funcao

		annotation SummarizationSetBy = Automatic

	column nome_funcao
		dataType: string
		lineageTag: a8235edc-787b-445e-804a-a007c3a99e90
		summarizeBy: none
		sourceColumn: nome_funcao

		annotation SummarizationSetBy = Automatic

	column codigo_programa
		dataType: string
		lineageTag: f589bc8e-fad1-4740-b583-3e13a5345483
		summarizeBy: none
		sourceColumn: codigo_programa

		annotation SummarizationSetBy = Automatic

	column nome_programa
		dataType: string
		lineageTag: e3e830e8-6da4-45e4-8489-52aa633d1a59
		summarizeBy: none
		sourceColumn: nome_programa

		annotation SummarizationSetBy = Automatic

	column codigo_acao
		dataType: string
		lineageTag: ff5f3a30-1540-4e45-b601-6cc4d606cc71
		summarizeBy: none
		sourceColumn: codigo_acao

		annotation SummarizationSetBy = Automatic

	column nome_acao
		dataType: string
		lineageTag: 97c92572-083a-493b-ac4f-1fce5803883d
		summarizeBy: none
		sourceColumn: nome_acao

		annotation SummarizationSetBy = Automatic

	column codigo_grupo_despesa
		dataType: string
		lineageTag: acc80fdf-d9a5-42e2-8c4a-dcefb075d815
		summarizeBy: none
		sourceColumn: codigo_grupo_despesa

		annotation SummarizationSetBy = Automatic

	column nome_grupo_despesa
		dataType: string
		lineageTag: 23982519-c119-4dd8-a83d-661d2deb76a0
		summarizeBy: none
		sourceColumn: nome_grupo_despesa

		annotation SummarizationSetBy = Automatic

	column valor_empenhado
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 79e00d9e-8180-410f-ba8e-9517170a945e
		summarizeBy: sum
		sourceColumn: valor_empenhado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column valor_liquidado
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 29ffc65e-72cf-4153-a662-bc4ec2a00e85
		summarizeBy: sum
		sourceColumn: valor_liquidado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column valor_pago
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 64bc7563-82fc-4e3b-9a86-28d97d1c3002
		summarizeBy: sum
		sourceColumn: valor_pago

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column valor_restos_pagos
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a71ca4c3-f64b-4ff4-995d-80c26b234031
		summarizeBy: sum
		sourceColumn: valor_restos_pagos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column classificacao_programa_divida
		dataType: string
		lineageTag: b824464d-d303-4930-82e4-8ac700ffb750
		summarizeBy: none
		sourceColumn: classificacao_programa_divida

		annotation SummarizationSetBy = Automatic

	column Orgao = [codigo_orgao_superior] & " — " & [nome_orgao_superior]
		dataType: string
		lineageTag: 3258e37e-2e2e-55fa-9c5b-c20445323d87
		summarizeBy: none

	column Funcao = [codigo_funcao] & " — " & [nome_funcao]
		dataType: string
		lineageTag: 0e356927-9045-5407-b3af-d68a7621a63b
		summarizeBy: none

	column Programa = [codigo_programa] & " — " & [nome_programa]
		dataType: string
		lineageTag: 6cfb05b3-2476-50cf-bfb2-5838cf9a2b2a
		summarizeBy: none

	column Acao = [codigo_acao] & " — " & [nome_acao]
		dataType: string
		lineageTag: 3330ddeb-5b0a-5e07-b924-4ca5de6b21a1
		summarizeBy: none

	hierarchy 'Classificação Orçamentária'
		lineageTag: 66c09234-90c5-4381-ac9f-a4c98ccc0d31

		level Órgão
			lineageTag: 02af5e64-945a-4dd7-a23e-50e575546acb
			column: Orgao

		level Função
			lineageTag: 5b71d3a1-2489-4266-8ad9-7164066b60db
			column: Funcao

		level Programa
			lineageTag: 2cf46969-6903-4c23-b11a-ec36f472e762
			column: Programa

		level Ação
			lineageTag: cf4522f4-1255-4901-9d76-a60c9196b892
			column: Acao

	partition despesas_bi = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\CAMINHO_DO_PROJETO\data\processed\despesas_bi.csv"),[Delimiter=";", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Alterar Tipo" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Alterar Tipo", [PromoteAllScalars=true]),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos", {{"periodo", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"valor_liquidado", Currency.Type}, {"valor_pago", Currency.Type}, {"valor_restos_pagos", Currency.Type}, {"valor_empenhado", Currency.Type}}, "en-US")
				in
				    #"Tipo Alterado com Localidade1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table
